name: Build SF CLI (Full) + SFDX Scanner

on:
  workflow_dispatch:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/login-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile_slim --tag ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}

      - name: Docker Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_slim
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-slim:latest